### ISSUE TITLE
Global refactoring

### ISSUE THREAD

**Issue by T1xx1** [kisvegabor/abbreviations-in-code#27]
Topic
- key-value pairs (_Originally posted by @kisvegabor in https://github.com/kisvegabor/abbreviations-in-code/issues/20#issuecomment-1385924428_)
- indentation

**Comment by T1xx1** [comment]
I've got an idea of how to format the list.

We are swapping abbrs and words. [Discussion](https://github.com/kisvegabor/abbreviations-in-code/pull/20#issuecomment-1385924428)
We keep words sorted in alphabetical order because it's easy to find things.
Each word has children (abbrs) made with indentation.
Children are sorted by recommendation degree so 🟢, 🟡 and lastly 🔴. Each word must get only 1 🟢 but can have multiple 🔴 and 🟡.
If we have multiple abbrs with the same degree there will be multiple lines sorted in alphabetical order.

E.g.
```
- a
 - 🟢 abbr
- b
 - 🟢 abbr
 - 🟡 abbr {context}
 - 🔴 abbr
- c
 - 🟢 abbr
 - 🟡 a {context}
 - 🟡 b {context}
 - 🔴 a
 - 🔴 b 
```

What do you think?

**Comment by philipeachille** [comment]
I think we should move towards a guideline list, in which we decide on the best abbrev and not even list the alternatives, unless a context-sensitive one is really good to use sometimes. Red ones should not even be listed much, if at all, because otherwise we could list an endless amount of abbrevs.

**Comment by T1xx1** [comment]
The part of having many abbr is not the problem (we can add them one by one in the time) because if we chose only one green for a word there will be only a correspondence (one key one value) (yellow apart). Red are important because they make people see that the choice they made over the abbr is not the best and change to the one we have marked as green.

**Comment by kisvegabor** [comment]
> Each word must get only 1 green_circle but can have multiple red_circle and yellow_circle.

I'm not sure about it. Let's say "radius" shouldn't be abbreviated but it can have 
- :yellow_circle: r
- :red_circle: rad

So I'd says
- <= 1 green
- <= 1 yellow
- \>= 0 red

For `{context}` I'd say `{comment}`. E.g.
- minimum
  - :green_circle: min 
- minute
  - :yellow_circle: min {can be mixed with minimum}

**Comment by philipeachille** [comment]
If, and I am only saying if, this list becomes a guideline to projects and teams then the red abbrevs are not needed, because the non-existence of an abbrev is then self-explanatory. If however the ist is more of a loose recommendation then yes, the red versions are a useful addition

**Comment by T1xx1** [comment]
:red_circle: are not "non existance" but not recommended to use. If we follow your logic for example someone new finding this list and not fetching the abbr they were looking for, maybe could think is a good idea to open an issue as they want their abbr to be added. Which in some case may result to be a bad abbr marked before with a red dot and then removed. With keeping red dot we avoid any unsure situations.

**Comment by kisvegabor** [comment]
I'm afraid, in the end we will have 1 green, 1 yellow, and 8 red for word. Maybe we should use red only for obvious but for some reason non-good abbreviations. E.g. "copy"->"cpy", "radius"->"rad".  So my though above can be updated like this:
- <= 1 green
- <= 1 yellow
- <= 3 red   (the most common, and intuitive abbreviations which are actually not good)


In CONTRIBUTION.md we can say when you open a PR for
- A new word: show how you compared the options, why you think that your suggestion is the best, etc
- For updating an existing word:  show metrics to prove that your suggestion is better.

We can also have PR templates with these questions.

**Comment by T1xx1** [comment]
Sure. That's a file called ISSUE_TEPLATES.md same as CONTRIBUTING.MD and README.md. It also increase repo's community guidelines.
