### ISSUE TITLE
Octal

### ISSUE THREAD

**Issue by T1xx1** [kisvegabor/abbreviations-in-code#31]
# ➕ New abbr

## Criteria

- Not an acronym (e.g. **RAM, CPU, SQL**) or a conventions (e.g. **i, j, k**).
- Lowercase
- Singular and neutral form.
- Max 1 🟢 abbr

<br>

### Octal • 🟢 oct

<br>

## Pros
- In the list, there are already binary, decimal and hexadecimal.

## Cons
- 

<br>

---

- [x] I can handle the following pr related to this issue to add the new abbr.

**Comment by kisvegabor** [comment]
Once we have `dec`, `bin` and `hex` we should have `oct` for sure too.

**Comment by T1xx1** [comment]
Add in #50
