### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by T1xx1** [kisvegabor/abbreviations-in-code#32]
# ➕ New abbr

## Criteria

- Not an acronym (e.g. **RAM, CPU, SQL**) or a conventions (e.g. **i, j, k**).
- Lowercase
- Singular and neutral form.
- Max 1 🟢 abbr

<br>

### Typescript • 🟢 ts

<br>

## Pros
- In the list, there's Javascript • js

## Cons
- 

<br>

---

- [x] I can handle the following pr related to this issue to add the new abbr.

**Comment by kisvegabor** [comment]
It's really the de facto abbreviation for TypeScript so I'm ok with that.

**Comment by T1xx1** [comment]
Added in #50
