### ISSUE TITLE
Initialization

### ISSUE THREAD

**Issue by T1xx1** [kisvegabor/abbreviations-in-code#36]
# ➕ New abbr

## Criteria

- Not an acronym (e.g. **RAM, CPU, SQL**) or a conventions (e.g. **i, j, k**).
- Lowercase
- Singular and neutral form.
- Max 1 🟢 abbr

<br>

### Initialization • 🟢 init

<br>

## Pros
- In the list, there's initialize • init

## Cons
- 

<br>

---

- [x] I can handle the following pr related to this issue to add the new abbr.

**Comment by kisvegabor** [comment]
I like it too.
