### ISSUE TITLE
Utilities

### ISSUE THREAD

**Issue by T1xx1** [kisvegabor/abbreviations-in-code#40]
# ➕ New abbr

## Criteria

- Not an acronym (e.g. **RAM, CPU, SQL**) or a conventions (e.g. **i, j, k**).
- Lowercase
- Singular and neutral form.
- Max 1 🟢 abbr

<br>

### utilities • 🟢 utils

<br>

## Pros
- 

## Cons
- 

<br>

---

- [x] I can handle the following pr related to this issue to add the new abbr.

**Comment by kisvegabor** [comment]
To follow the "Singular and neutral form" rule shouldn't it be 
utility • :green_circle: util ?

**Comment by T1xx1** [comment]
> To follow the "Singular and neutral form" rule shouldn't it be utility • 🟢 util ?

Actually, it should be.
This makes me think also about the adjectives we add before. Shouldn't we convert them into nouns?

**Comment by kisvegabor** [comment]
For example which ones do you mean?

**Comment by T1xx1** [comment]
Like those ones:

developer (noun) development (adj) (that could pass tho)
initialize (noun) initialization (adj)
selection (noun) selected (that's a verb...) (select's missing)
synchronous (noun) synchronize (verb)

Btw 'synchronous' is missing the dot.

**Comment by kisvegabor** [comment]
> initialize (noun) initialization (adj)

Isn't it
- initialization: noun
- initialized: adj
- initialize: verb

---

- selection: noun 
- selected: adj 
- select: verb

---

- synchronization: noun
- synchronous: adj
- synchronize: verb

Anyway, I'm not entirely sure what "neutral form" means. I think we should agree on the preferred word-class. Noun seems the best to me, but as non native speaker I'm not familiar with the English grammar. :sweat_smile: 

> Btw 'synchronous' is missing the dot.

Fixed.

**Comment by T1xx1** [comment]
> > initialize (noun) initialization (adj)
> 
> Isn't it
> - initialization: noun
> - initialized: adj
> - initialize: verb
> 
> ---
> 
> - selection: noun 
> - selected: adj 
> - select: verb
> 
> ---
> 
> - synchronization: noun
> - synchronous: adj
> - synchronize: verb

Ops made some mistakes. 


> Anyway, I'm not entirely sure what "neutral form" means.

We should specify neutral as singular masculine and noun so that's neutral following how dictionaries do.


> but as non native speaker I'm not familiar with the English grammar. :sweat_smile: 

Neither am I. HAHAHA


> > Btw 'synchronous' is missing the dot.
> 
> I can't find it the README. We have only "asynchronous" which has a dot.

![Screenshot_20230227_102803.jpg](https://user-images.githubusercontent.com/69322987/221525785-75c108d5-a14d-472a-9450-8c039f9ee8c8.jpg)

**Comment by kisvegabor** [comment]
> We should specify neutral as singular masculine and noun so that's neutral following how dictionaries do.

I'm ok with that. Especially if it's already a practice for dictionaries. 


>> Btw 'synchronous' is missing the dot.
> I can't find it the README. We have only "asynchronous" which has a dot.
[...]

Thanks,  seemingly I'm blind :slightly_smiling_face:

**Comment by kisvegabor** [comment]
Amazing!

**Comment by T1xx1** [comment]
Added in #50
